"use client";

import { useState, useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import { motion, AnimatePresence } from "framer-motion";
import {
  FileText, Wand2, Copy, Check, Download, AlertTriangle,
  User, Briefcase, GraduationCap, Zap, ThumbsUp, ThumbsDown,
} from "lucide-react";
import { pushNotif } from "@/lib/notifications";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import NoCreditsModal from "./NoCreditsModal";
import LimitReachedModal from "./LimitReachedModal";
import { useUserProfile } from "@/hooks/useUserProfile";
import { CREDITS } from "@/lib/credits";

/* ── Professional PDF export — fixed A4 layout, no clipping ─────────────── */
async function exportResumePDF(markdownContent: string, fullName: string) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const jspdfMod: any = await import("jspdf");
  const JsPDF = jspdfMod.jsPDF ?? jspdfMod.default;
  const doc = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const PW = 210, PH = 297;
  const ML = 18, MR = 18, MT = 24, MB = 22;
  const CW = PW - ML - MR;

  let y = MT;

  const newPage = () => { doc.addPage(); y = MT; };

  const drawLines = (
    text: string,
    fontSize: number,
    fontStyle: "normal" | "bold",
    rgb: [number, number, number],
    indent = 0,
    extraGap = 0,
  ) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", fontStyle);
    doc.setTextColor(rgb[0], rgb[1], rgb[2]);
    const lh = fontSize * 0.3528 * 1.28;
    const wrapped = doc.splitTextToSize(text, CW - indent);
    for (const wLine of wrapped) {
      if (y + lh > PH - MB) newPage();
      doc.text(wLine, ML + indent, y);
      y += lh;
    }
    y += extraGap;
  };

  const clean = (s: string) =>
    s.replace(/\*\*(.+?)\*\*/g, "$1")
     .replace(/\*(.+?)\*/g, "$1")
     .replace(/`(.+?)`/g, "$1")
     .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");

  for (const raw of markdownContent.split("\n")) {
    const line = raw.trim();

    if (line.startsWith("# ")) {
      if (y > MT + 2) y += 2;
      if (y + 12 > PH - MB) newPage();
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(10, 36, 99);
      doc.text(line.slice(2), ML, y);
      y += 10;

    } else if (line.startsWith("## ")) {
      y += 4;
      if (y + 10 > PH - MB) newPage();
      doc.setFontSize(10.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(79, 70, 229);
      doc.text(line.slice(3).toUpperCase(), ML, y);
      y += 1.5;
      if (y + 1 > PH - MB) newPage();
      doc.setDrawColor(79, 70, 229);
      doc.setLineWidth(0.35);
      doc.line(ML, y + 1, PW - MR, y + 1);
      y += 5.5;

    } else if (line.startsWith("### ")) {
      y += 1;
      drawLines(clean(line.slice(4)), 10, "bold", [30, 41, 59], 0, 1);

    } else if (line.startsWith("- ") || line.startsWith("• ")) {
      const txt = clean(line.replace(/^[-•]\s/, ""));
      doc.setFontSize(9.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(55, 65, 80);
      const lh = 9.5 * 0.3528 * 1.28;
      const wrapped = doc.splitTextToSize(txt, CW - 6);
      for (let i = 0; i < wrapped.length; i++) {
        if (y + lh > PH - MB) newPage();
        if (i === 0) {
          doc.setFillColor(79, 70, 229);
          doc.circle(ML + 1.8, y - 1.4, 0.75, "F");
        }
        doc.text(wrapped[i], ML + 5, y);
        y += lh;
      }
      y += 0.5;

    } else if (line.match(/^---+$/) || line.match(/^___+$/)) {
      y += 2;
      if (y + 2 > PH - MB) newPage();
      doc.setDrawColor(200, 212, 225);
      doc.setLineWidth(0.25);
      doc.line(ML, y, PW - MR, y);
      y += 3;

    } else if (line.length > 0) {
      drawLines(clean(line), 9.5, "normal", [55, 65, 80], 0, 1);
    } else {
      y += 2;
    }
  }

  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by AI Nexus  ·  Page ${p} of ${total}`,
      PW / 2, PH - 10,
      { align: "center" }
    );
  }

  doc.save(`${fullName.replace(/\s+/g, "_") || "resume"}.pdf`);
}

/* ── Types ───────────────────────────────────────────────────────────────── */
interface FormData {
  fullName:   string;
  jobTitle:   string;
  email:      string;
  phone:      string;
  linkedin:   string;
  summary:    string;
  experience: string;
  skills:     string;
  education:  string;
}

const EMPTY: FormData = {
  fullName: "", jobTitle: "", email: "", phone: "", linkedin: "",
  summary: "", experience: "", skills: "", education: "",
};

const TABS = [
  { id: "personal",   label: "Personal",   icon: User },
  { id: "experience", label: "Experience", icon: Briefcase },
  { id: "education",  label: "Education",  icon: GraduationCap },
  { id: "skills",     label: "Skills",     icon: Zap },
] as const;

type TabId = typeof TABS[number]["id"];

/* ── Preview markdown — paper/light styling ──────────────────────────────── */
const previewMd: React.ComponentProps<typeof ReactMarkdown>["components"] = {
  h1: ({ children }) => (
    <h1 style={{ fontFamily: "'Inter', sans-serif" }}
      className="text-xl font-bold text-slate-800 pb-2 mb-2 border-b-2 border-indigo-200">
      {children}
    </h1>
  ),
  h2: ({ children }) => (
    <h2 style={{ fontFamily: "'Inter', sans-serif" }}
      className="text-[11px] font-bold text-indigo-600 uppercase tracking-widest mt-5 mb-2 pb-1 border-b border-indigo-100">
      {children}
    </h2>
  ),
  h3: ({ children }) => (
    <h3 style={{ fontFamily: "'Inter', sans-serif" }}
      className="text-sm font-semibold text-slate-700 mt-3 mb-0.5">
      {children}
    </h3>
  ),
  p: ({ children }) => (
    <p style={{ fontFamily: "'Inter', sans-serif" }}
      className="text-sm text-slate-600 mb-2 leading-relaxed">
      {children}
    </p>
  ),
  ul: ({ children }) => <ul className="space-y-1 mb-3">{children}</ul>,
  li: ({ children }) => (
    <li style={{ fontFamily: "'Inter', sans-serif" }}
      className="flex items-start gap-2 text-sm text-slate-600">
      <span className="mt-[7px] w-1.5 h-1.5 rounded-full bg-indigo-400 flex-shrink-0" />
      <span>{children}</span>
    </li>
  ),
  strong: ({ children }) => (
    <strong style={{ fontFamily: "'Inter', sans-serif" }} className="font-semibold text-slate-800">
      {children}
    </strong>
  ),
  hr: () => <hr className="my-3 border-slate-200" />,
};

/* ── Live preview builder from raw form data ─────────────────────────────── */
function buildPreviewMarkdown(form: FormData): string {
  const lines: string[] = [];

  if (form.fullName)  lines.push(`# ${form.fullName}`);
  if (form.jobTitle)  lines.push(`**${form.jobTitle}**`);

  const contact = [form.email, form.phone, form.linkedin].filter(Boolean).join("  ·  ");
  if (contact) lines.push(contact);

  if (form.summary)    { lines.push("", "## Summary",    form.summary); }
  if (form.experience) { lines.push("", "## Experience", form.experience); }
  if (form.education)  { lines.push("", "## Education",  form.education); }
  if (form.skills)     { lines.push("", "## Skills",     form.skills); }

  return lines.join("\n");
}

/* ── Input styles ─────────────────────────────────────────────────────────── */
const INPUT_CLS  = "w-full px-3.5 py-2.5 text-sm rounded-lg border border-slate-200 bg-white text-slate-800 placeholder-slate-300 outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-50 transition-all";
const TA_CLS     = "w-full px-3.5 py-2.5 text-sm rounded-lg border border-slate-200 bg-white text-slate-800 placeholder-slate-300 outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-50 transition-all resize-none";
const LABEL_CLS  = "block text-xs font-medium text-slate-500 mb-1.5";

/* ════════════════════════════════════════════════════════════════════════════ */
export default function ResumeBuilder({ onOpenSubscription }: { onOpenSubscription?: () => void }) {
  const [form,         setForm]         = useState<FormData>(EMPTY);
  const [loading,      setLoading]      = useState(false);
  const [resume,       setResume]       = useState("");
  const [error,        setError]        = useState<string | null>(null);
  const [copied,       setCopied]       = useState(false);
  const [pdfLoading,   setPdfLoading]   = useState(false);
  const [noCreditsOpen, setNoCreditsOpen] = useState(false);
  const [limitOpen,    setLimitOpen]    = useState(false);
  const [limitHours,   setLimitHours]   = useState(24);
  const [limitUsed,    setLimitUsed]    = useState(3);
  const [toast,        setToast]        = useState<string | null>(null);
  const [mounted,      setMounted]      = useState(false);
  const [activeTab,    setActiveTab]    = useState<TabId>("personal");
  const [mobilePanel,  setMobilePanel]  = useState<"edit" | "preview">("edit");
  const prevTabIdx = useRef(0);

  const { profile, refetch: refetchProfile } = useUserProfile();

  useEffect(() => { setMounted(true); }, []);

  const showToast = (text: string) => {
    setToast(text);
    setTimeout(() => setToast(null), 3500);
  };

  const set = (key: keyof FormData) => (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => setForm((f) => ({ ...f, [key]: e.target.value }));

  const handleTabChange = (id: TabId) => {
    prevTabIdx.current = TABS.findIndex(t => t.id === activeTab);
    setActiveTab(id);
  };

  const handleGenerate = async () => {
    if (!form.fullName.trim() || !form.experience.trim() || loading) return;
    setLoading(true);
    setError(null);
    setResume("");
    setMobilePanel("preview");

    try {
      const res = await fetch("/api/generate-resume", {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify(form),
      });

      if (res.status === 403) {
        setNoCreditsOpen(true);
        pushNotif({ title: "Credits Exhausted", sub: "No credits left for Resume Builder.", type: "error" });
        return;
      }
      if (res.status === 429) {
        const d = await res.json().catch(() => ({}));
        setLimitHours(d.resetInHours ?? 24);
        setLimitUsed(d.used ?? CREDITS.DAILY_RESUME_LIMIT);
        setLimitOpen(true);
        pushNotif({ title: "Daily Resume Limit Reached", sub: `${CREDITS.DAILY_RESUME_LIMIT} resumes/day — resets in ${d.resetInHours ?? 24}h`, type: "warning" });
        return;
      }
      if (!res.ok || !res.body) {
        const d = await res.json().catch(() => ({}));
        setError(d.message ?? d.error ?? `Error ${res.status}`);
        return;
      }

      const reader  = res.body.getReader();
      const decoder = new TextDecoder();
      let   buf     = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buf += decoder.decode(value, { stream: true });
        setResume(buf);
      }

      if (!buf.trim()) setError("Empty response — please try again.");
      await refetchProfile();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Network error");
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(resume);
    setCopied(true);
    showToast("Resume copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMd = () => {
    const blob = new Blob([resume], { type: "text/markdown" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `${form.fullName.replace(/\s+/g, "_") || "resume"}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = async () => {
    if (!resume || pdfLoading) return;
    setPdfLoading(true);
    try {
      await exportResumePDF(resume, form.fullName);
      showToast("PDF downloaded successfully!");
    } catch (err) {
      showToast("PDF export failed — please try again.");
      console.error("[PDF export]", err);
    } finally {
      setPdfLoading(false);
    }
  };

  const displayContent = resume || buildPreviewMarkdown(form);
  const canGenerate    = !!form.fullName.trim() && !!form.experience.trim() && !loading;

  /* ── Tab content per panel ─────────────────────────────────────────────── */
  const tabVariants = {
    enter:  { opacity: 0, y: 8 },
    center: { opacity: 1, y: 0 },
    exit:   { opacity: 0, y: -8 },
  };

  const renderTabContent = () => (
    <AnimatePresence mode="wait">
      {activeTab === "personal" && (
        <motion.div key="personal"
          variants={tabVariants} initial="enter" animate="center" exit="exit"
          transition={{ duration: 0.18 }}
          className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className={LABEL_CLS}>Full Name <span className="text-red-400">*</span></label>
              <input className={INPUT_CLS} value={form.fullName} onChange={set("fullName")} placeholder="Jane Doe" />
            </div>
            <div>
              <label className={LABEL_CLS}>Job Title</label>
              <input className={INPUT_CLS} value={form.jobTitle} onChange={set("jobTitle")} placeholder="Senior Engineer" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className={LABEL_CLS}>Email</label>
              <input className={INPUT_CLS} type="email" value={form.email} onChange={set("email")} placeholder="jane@example.com" />
            </div>
            <div>
              <label className={LABEL_CLS}>Phone</label>
              <input className={INPUT_CLS} value={form.phone} onChange={set("phone")} placeholder="+1 555-0100" />
            </div>
          </div>
          <div>
            <label className={LABEL_CLS}>LinkedIn / Portfolio</label>
            <input className={INPUT_CLS} value={form.linkedin} onChange={set("linkedin")} placeholder="linkedin.com/in/janedoe" />
          </div>
          <div>
            <label className={LABEL_CLS}>Professional Summary</label>
            <textarea className={TA_CLS} rows={4} value={form.summary} onChange={set("summary")}
              placeholder="Results-driven engineer with 6 years of experience building scalable SaaS products…" />
          </div>
        </motion.div>
      )}

      {activeTab === "experience" && (
        <motion.div key="experience"
          variants={tabVariants} initial="enter" animate="center" exit="exit"
          transition={{ duration: 0.18 }}
          className="space-y-4">
          <div>
            <label className={LABEL_CLS}>Work Experience <span className="text-red-400">*</span></label>
            <p className="text-xs text-slate-400 mb-2">Each role on a new line. Use bullet points (•) for achievements.</p>
            <textarea className={TA_CLS} rows={12} value={form.experience} onChange={set("experience")}
              placeholder={"Senior Engineer @ Acme Corp (2021–Present)\n• Led migration to microservices, reducing latency by 40%\n• Mentored 3 junior developers\n\nEngineer @ StartupXYZ (2019–2021)\n• Built React dashboard used by 10K users"} />
          </div>
        </motion.div>
      )}

      {activeTab === "education" && (
        <motion.div key="education"
          variants={tabVariants} initial="enter" animate="center" exit="exit"
          transition={{ duration: 0.18 }}
          className="space-y-4">
          <div>
            <label className={LABEL_CLS}>Education</label>
            <textarea className={TA_CLS} rows={6} value={form.education} onChange={set("education")}
              placeholder={"B.Sc. Computer Science · MIT · 2019\nGPA 3.8 · Dean's List 2017–2019"} />
          </div>
        </motion.div>
      )}

      {activeTab === "skills" && (
        <motion.div key="skills"
          variants={tabVariants} initial="enter" animate="center" exit="exit"
          transition={{ duration: 0.18 }}
          className="space-y-4">
          <div>
            <label className={LABEL_CLS}>Technical Skills</label>
            <p className="text-xs text-slate-400 mb-2">Comma-separated list of technologies and tools.</p>
            <textarea className={TA_CLS} rows={4} value={form.skills} onChange={set("skills")}
              placeholder="TypeScript, React, Node.js, PostgreSQL, Docker, AWS, GraphQL" />
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );

  /* ── Preview panel content ──────────────────────────────────────────────── */
  const renderPreview = () => (
    <div className="flex-1 overflow-y-auto p-5 lg:p-6">
      {loading ? (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-8 max-w-2xl mx-auto">
          <div className="space-y-3 animate-pulse">
            <div className="h-6 bg-slate-100 rounded w-48" />
            <div className="h-3 bg-slate-100 rounded w-32" />
            <div className="h-3 bg-slate-100 rounded w-64 mt-4" />
            <div className="space-y-2 mt-4">
              {[80, 60, 90, 55, 75].map((w, i) => (
                <div key={i} className="h-3 bg-slate-100 rounded" style={{ width: `${w}%` }} />
              ))}
            </div>
          </div>
          <p className="text-xs text-slate-400 text-center mt-6 font-medium">Crafting your resume…</p>
        </div>
      ) : displayContent ? (
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.22 }}
          className="bg-white rounded-xl border border-slate-200 shadow-sm p-8 max-w-2xl mx-auto"
          style={{ fontFamily: "'Inter', sans-serif" }}
        >
          <ReactMarkdown remarkPlugins={[remarkGfm]} components={previewMd}>
            {displayContent}
          </ReactMarkdown>
        </motion.div>
      ) : (
        <div className="flex flex-col items-center justify-center h-full text-center py-16">
          <div className="w-14 h-14 rounded-2xl bg-indigo-50 border border-indigo-100 flex items-center justify-center mb-4">
            <FileText className="w-6 h-6 text-indigo-400" />
          </div>
          <p className="text-sm font-semibold text-slate-700 mb-1">Your preview appears here</p>
          <p className="text-xs text-slate-400 max-w-48">Fill in your details on the left — the preview updates live as you type.</p>
        </div>
      )}
    </div>
  );

  return (
    <>
      <NoCreditsModal isOpen={noCreditsOpen} onClose={() => setNoCreditsOpen(false)}
        required={CREDITS.DAILY_RESUME_LIMIT} current={profile?.credits}
        onUpgrade={onOpenSubscription} />
      <LimitReachedModal isOpen={limitOpen} onClose={() => setLimitOpen(false)}
        type="resume" resetInHours={limitHours} used={limitUsed} limit={CREDITS.DAILY_RESUME_LIMIT} />

      {mounted && createPortal(
        <AnimatePresence>
          {toast && (
            <motion.div key="resume-toast"
              initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 24 }} transition={{ duration: 0.22 }}
              className="fixed bottom-8 left-1/2 -translate-x-1/2 z-[999] flex items-center gap-2.5 px-5 py-3 rounded-2xl pointer-events-none shadow-xl"
              style={{ background: "rgba(30,41,59,0.97)", border: "1px solid rgba(100,116,139,0.3)" }}>
              <span className="w-1.5 h-1.5 rounded-full bg-indigo-400" />
              <span className="text-sm font-medium text-slate-100 whitespace-nowrap"
                style={{ fontFamily: "'Inter', sans-serif" }}>
                {toast}
              </span>
            </motion.div>
          )}
        </AnimatePresence>,
        document.body
      )}

      <div className="flex flex-col flex-1 min-h-0 overflow-hidden bg-slate-50">

        {/* ── Global header ─────────────────────────────────────────────── */}
        <div className="flex items-center justify-between px-5 py-3 bg-white border-b border-slate-200 flex-shrink-0">
          <div>
            <h2 className="text-sm font-semibold text-slate-800" style={{ fontFamily: "'Inter', sans-serif" }}>
              Resume Builder
            </h2>
            <p className="text-xs text-slate-400 mt-0.5" style={{ fontFamily: "'Inter', sans-serif" }}>
              ATS-optimised · AI-powered · {CREDITS.DAILY_RESUME_LIMIT} free/day
            </p>
          </div>
          <div className="flex items-center gap-2">
            {profile && (
              <span className="text-xs font-semibold text-indigo-600 bg-indigo-50 px-3 py-1.5 rounded-full border border-indigo-100"
                style={{ fontFamily: "'Inter', sans-serif" }}>
                {profile.credits} credits
              </span>
            )}
            {/* Mobile panel toggle */}
            <div className="flex lg:hidden rounded-lg border border-slate-200 overflow-hidden">
              {(["edit", "preview"] as const).map(p => (
                <button key={p} onClick={() => setMobilePanel(p)}
                  className={`px-3 py-1.5 text-xs font-medium transition-colors ${
                    mobilePanel === p
                      ? "bg-indigo-600 text-white"
                      : "bg-white text-slate-500 hover:bg-slate-50"
                  }`}
                  style={{ fontFamily: "'Inter', sans-serif" }}>
                  {p === "edit" ? "Edit" : "Preview"}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* ── Split-screen body ─────────────────────────────────────────── */}
        <div className="flex flex-1 min-h-0 overflow-hidden flex-col lg:flex-row">

          {/* LEFT: Form panel */}
          <div className={`w-full lg:w-[44%] flex flex-col bg-white border-r border-slate-200 overflow-hidden ${
            mobilePanel === "preview" ? "hidden lg:flex" : "flex"
          }`}>

            {/* Section tabs */}
            <div className="flex border-b border-slate-200 flex-shrink-0">
              {TABS.map(tab => {
                const Icon = tab.icon;
                const active = activeTab === tab.id;
                return (
                  <button key={tab.id} onClick={() => handleTabChange(tab.id)}
                    className="flex-1 py-3 flex flex-col items-center gap-1 relative transition-colors"
                    style={{ fontFamily: "'Inter', sans-serif" }}>
                    <Icon className={`w-4 h-4 transition-colors ${active ? "text-indigo-600" : "text-slate-400"}`} />
                    <span className={`text-[10px] font-medium transition-colors ${active ? "text-indigo-600" : "text-slate-400"}`}>
                      {tab.label}
                    </span>
                    {active && (
                      <motion.div layoutId="tab-underline"
                        className="absolute bottom-0 left-1 right-1 h-0.5 bg-indigo-500 rounded-full"
                        transition={{ type: "spring", stiffness: 500, damping: 40 }} />
                    )}
                  </button>
                );
              })}
            </div>

            {/* Tab form content */}
            <div className="flex-1 overflow-y-auto p-5">
              {renderTabContent()}
            </div>

            {/* Generate button */}
            <div className="p-4 border-t border-slate-100 space-y-3 flex-shrink-0">
              <AnimatePresence>
                {error && (
                  <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }}
                    exit={{ opacity: 0, height: 0 }} transition={{ duration: 0.18 }}
                    className="flex items-start gap-2.5 px-3.5 py-2.5 rounded-lg bg-red-50 border border-red-100">
                    <AlertTriangle className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />
                    <p className="text-sm text-red-600" style={{ fontFamily: "'Inter', sans-serif" }}>{error}</p>
                  </motion.div>
                )}
              </AnimatePresence>

              <motion.button
                onClick={handleGenerate}
                disabled={!canGenerate}
                whileHover={canGenerate ? { y: -1 } : {}}
                whileTap={canGenerate ? { scale: 0.98 } : {}}
                className="w-full py-3 rounded-xl text-sm font-semibold text-white flex items-center justify-center gap-2.5 disabled:opacity-40 disabled:cursor-not-allowed transition-all shadow-md shadow-indigo-200"
                style={{
                  fontFamily: "'Inter', sans-serif",
                  background: loading
                    ? "rgba(99,102,241,0.5)"
                    : "linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)",
                }}
              >
                {loading ? (
                  <>
                    <motion.div animate={{ rotate: 360 }} transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                      className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full" />
                    Crafting your resume…
                  </>
                ) : (
                  <>
                    <Wand2 className="w-4 h-4" />
                    Generate Resume
                  </>
                )}
              </motion.button>
            </div>
          </div>

          {/* RIGHT: Preview panel */}
          <div className={`flex-1 flex flex-col bg-slate-50 overflow-hidden ${
            mobilePanel === "edit" ? "hidden lg:flex" : "flex"
          }`}>

            {/* Preview toolbar */}
            <div className="flex items-center justify-between px-5 py-3 bg-white border-b border-slate-200 flex-shrink-0">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-indigo-500" />
                <span className="text-xs font-semibold text-slate-600"
                  style={{ fontFamily: "'Inter', sans-serif" }}>
                  {resume ? "Generated Resume" : "Live Preview"}
                </span>
                {loading && (
                  <motion.div animate={{ rotate: 360 }} transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                    className="w-3.5 h-3.5 border-2 border-indigo-100 border-t-indigo-500 rounded-full" />
                )}
              </div>

              <div className="flex items-center gap-1.5">
                {resume && (
                  <>
                    {/* Feedback */}
                    <motion.button whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}
                      onClick={() => showToast("Thanks! Glad the resume looks good.")}
                      className="w-7 h-7 rounded-lg flex items-center justify-center text-slate-300 hover:text-emerald-500 transition-colors">
                      <ThumbsUp className="w-3.5 h-3.5" />
                    </motion.button>
                    <motion.button whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}
                      onClick={() => showToast("Sorry! Try adding more details to the form.")}
                      className="w-7 h-7 rounded-lg flex items-center justify-center text-slate-300 hover:text-red-400 transition-colors">
                      <ThumbsDown className="w-3.5 h-3.5" />
                    </motion.button>

                    <div className="w-px h-4 bg-slate-200 mx-1" />

                    {/* Copy */}
                    <motion.button whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}
                      onClick={handleCopy}
                      className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-[11px] font-medium border border-slate-200 bg-white transition-colors hover:border-slate-300"
                      style={{ fontFamily: "'Inter', sans-serif", color: copied ? "#16a34a" : "#64748b" }}>
                      {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                      {copied ? "Copied" : "Copy"}
                    </motion.button>

                    {/* .md download */}
                    <motion.button whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}
                      onClick={handleDownloadMd}
                      className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-[11px] font-medium text-slate-500 border border-slate-200 bg-white transition-colors hover:border-slate-300"
                      style={{ fontFamily: "'Inter', sans-serif" }}>
                      <Download className="w-3 h-3" /> .md
                    </motion.button>
                  </>
                )}

                {/* Prominent PDF button */}
                <motion.button
                  whileHover={!pdfLoading && !!resume ? { y: -1, boxShadow: "0 4px 16px rgba(99,102,241,0.35)" } : {}}
                  whileTap={!pdfLoading && !!resume ? { scale: 0.97 } : {}}
                  onClick={handleDownloadPDF}
                  disabled={!resume || pdfLoading || loading}
                  className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-white transition-all disabled:opacity-40 disabled:cursor-not-allowed shadow-sm"
                  style={{
                    fontFamily: "'Inter', sans-serif",
                    background: "linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)",
                  }}>
                  {pdfLoading ? (
                    <motion.div animate={{ rotate: 360 }} transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                      className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full" />
                  ) : (
                    <Download className="w-3.5 h-3.5" />
                  )}
                  {pdfLoading ? "Exporting…" : "Download PDF"}
                </motion.button>
              </div>
            </div>

            {renderPreview()}
          </div>
        </div>
      </div>
    </>
  );
}
